some minor changes
* STDIN=$(cat) removed cause makes it always expect STDIN 
* add user and token function removed because of low usage and high maintenance
* now accepts message by stdin or argument

diff --git a/telebot b/telebot
--- a/telebot
+++ b/telebot
@@ -1,37 +1,40 @@
 #!/bin/bash
+
+## INIT__ 
+[[ -f $HOME/telebot/users ]] || touch $HOME/telebot/users #create users file if it doesn't exist
+[[ -f $HOME/telebot/token ]] || touch $HOME/telebot/token #create tokens file if it doesn't exist
 TOKEN=$(<$HOME/telebot/token)
 USER=$(<$HOME/telebot/users)
-=======
-STDIN=$(cat)
 
-MESSAGE=$STDIN
-################### Add bot
+
+################### token or files not found
 if [[ -z "$TOKEN" ]]; then
-	echo "No bot TOKEN specified.\nPlease add bot by sending:\ntelebot -b [token]"
+	echo -e "No bot TOKEN specified.\nPlease add bot API key to the token file"
 	exit 1
 fi
-if [[ $1 == "-b" ]]; then
-	echo "$2">>$HOME/telebot/token
-	exit 2
-fi
-################### Add user
-if [[ -z "$CHATID" ]]; then
-	echo "No user values found.\nPlease add users by sending:\ntelebot -a [user] [chatid]"
+if [[ -z "$USER" ]]; then
+	echo -e "No user values found.\nPlease add users to the users file using the following format:\n
+	[user] [chatid]"
 	exit 1
 fi
-if [[ $1 == "-a" ]]; then
-	echo "$2\t$3\n">>$HOME/telebot/users
-	exit 2
-fi
+
+
 ################### Send
 if [[ $1 == "-s" ]]; then
-	if [ $2 == "$(grep $USER "$2" | awk '{print $1}')" ]; then
-		CHATID="$(grep $USER "$2"| awk '{print $2}')"
+	if [ $2 == "$(echo $USER | grep $2 | awk '{print $1}')" ]; then
+		CHATID="$(echo $USER | grep $2 | awk '{print $2}')"
 	else
-		echo "Sorry, user was not found."
+		echo "Sorry, user \"$2\" was not found."
 		exit 1
 	fi
+	if [ ${#CHATID} != 9 ]; then
+		echo "Sorry, user \"$2\" CHATID has a unusual lenght and is most likely incorrect."
+		exit 1
+	
+	fi
+	MESSAGE=${3:-$(</dev/stdin)} #takes message input from $3, in case it is not set (null value), takes message from standard input (eg.: an echo piped)
 	curl -s -X POST https://api.telegram.org/bot$TOKEN/sendMessage -d chat_id=$CHATID -d text="$MESSAGE" -d parse_mode="markdown" > /dev/null
-	echo -e "Sent to $2: $MESSAGE"
+	echo -n "Sent to $2: "
+	echo -e $MESSAGE
 	exit 2
 fi
